"""Add tracking tables

Revision ID: c005cb98945a
Revises: 256c6b0d4b0f
Create Date: 2026-08-31 13:59:11.897036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c005cb98945a'
down_revision: Union[str, Sequence[str], None] = '256c6b0d4b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('problem_slug', sa.String(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visitor_id', 'problem_slug', name='uq_attempt_visitor_problem')
    )
    op.create_index(op.f('ix_attempts_problem_slug'), 'attempts', ['problem_slug'], unique=False)
    op.create_index(op.f('ix_attempts_visitor_id'), 'attempts', ['visitor_id'], unique=False)
    op.create_table('solves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('problem_slug', sa.String(), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visitor_id', 'problem_slug', name='uq_solve_visitor_problem')
    )
    op.create_index(op.f('ix_solves_problem_slug'), 'solves', ['problem_slug'], unique=False)
    op.create_index(op.f('ix_solves_visitor_id'), 'solves', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solves_visitor_id'), table_name='solves')
    op.drop_index(op.f('ix_solves_problem_slug'), table_name='solves')
    op.drop_table('solves')
    op.drop_index(op.f('ix_attempts_visitor_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_problem_slug'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_table('visitors')
    # ### end Alembic commands ###
